#define CLIB_TEST_DIMX 128
#define CLIB_TEST_DIMY 128
#define CLIB_TEST_ITEMS CLIB_TEST_DIMX*CLIB_TEST_DIMY
#define CLIB_TEST_NOISE 64
#define CLIB_TEST_CLUSTERS 4
#define CLIB_TEST_ITER 1
#define CLIB_TEST_THREADS 512
